version: 2

project_name: topn

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - main: ./cmd/topn
    binary: topn
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc

brews:
  - repository:
      owner: natemollica-nm
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/natemollica-nm/topn
    description: "Fast file size scanner to find and remove large files"
    license: MIT